language: python
python:
- 2.7
env:
  matrix:
  - DOCKER_CONTENT_TRUST=0
services:
- docker
before_install:
- sudo apt-get update
- docker-compose --version
- pip install docker-compose --upgrade
- docker-compose --version
install:
- cd 5.7
- docker-compose -f docker-compose-build.yml build
- docker-compose -f docker-compose-build.yml up -d
- docker-compose ps
- cd $TRAVIS_BUILD_DIR/5.7/configs/vault
- docker-compose up -d
before_script:
- pip install requests
- pip install docker
- cd $TRAVIS_BUILD_DIR/5.7
- docker cp configs/php/env.example web:/var/www/backend/.env
- docker-compose -f docker-compose-build.yml exec web composer install
- docker-compose -f docker-compose-build.yml restart web
- cd $TRAVIS_BUILD_DIR
script:
- bash ./.travis/linters.sh
- python tests.py
notifications:
  slack:
    rooms:
    - optimum-team:"$SLACK"#build
after_success:
- cd 5.7
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
- docker-compose -f docker-compose-build.yml images
- docker push trydirect/laravel:5.7
